import { SAMPLES } from './samples'
import type { PunchListResult, RoundDiff, Severity, Trade } from '../types'

export const DEMO_PROJECT_ID = 'demo'

export interface DemoPhoto {
  id: string
  label: string
  photoPath: string
  analysis: PunchListResult
}

export interface DemoItem {
  id: string
  title: string
  description: string
  location: string
  trade: Trade
  severity: Severity
  recommended_action: string
  sourcePhotoIds: string[]
}

export interface DemoRound {
  id: string
  index: number
  name: string
  projectSummary: string
  progressNotes: string
  photos: DemoPhoto[]
  items: DemoItem[]
  diff?: RoundDiff
}

const [crackedWall, basementWiring, waterDamageCeiling] = SAMPLES

// Round 1 reuses the three hand-reviewed sample photos/analyses so the demo
// needs zero API calls. The three scenes don't share a physical location, so
// consolidation here is a straight 1:1 pass-through with project-level
// locations — an honest reflection of what /aggregate would return for a
// set of unrelated areas (no invented merges).
const round1: DemoRound = {
  id: 'demo-r1',
  index: 1,
  name: 'Initial inspection',
  projectSummary:
    'Three areas inspected: an exterior retaining wall, a basement utility room mid rough-in, ' +
    'and an interior ceiling with active water damage. Each area has at least one high-severity ' +
    'issue requiring attention before work can proceed to the next stage.',
  progressNotes:
    'Site shows mixed progress across areas: exterior hardscape and retaining walls are built but ' +
    'show structural distress, basement electrical/plumbing rough-in is underway with wiring still ' +
    'unsecured, and at least one occupied-space ceiling needs remediation before finishes can start. ' +
    'No single trade is blocking the others yet, but the ceiling leak should be traced before it does.',
  photos: [
    { id: 'demo-cracked-wall', label: crackedWall.label, photoPath: crackedWall.photo, analysis: crackedWall.result },
    {
      id: 'demo-basement-wiring',
      label: basementWiring.label,
      photoPath: basementWiring.photo,
      analysis: basementWiring.result,
    },
    {
      id: 'demo-water-damage-ceiling',
      label: waterDamageCeiling.label,
      photoPath: waterDamageCeiling.photo,
      analysis: waterDamageCeiling.result,
    },
  ],
  items: [
    ...crackedWall.result.items.map((it) => toDemoItem('demo-r1', 'demo-cracked-wall', crackedWall.label, it)),
    ...basementWiring.result.items.map((it) =>
      toDemoItem('demo-r1', 'demo-basement-wiring', basementWiring.label, it),
    ),
    ...waterDamageCeiling.result.items.map((it) =>
      toDemoItem('demo-r1', 'demo-water-damage-ceiling', waterDamageCeiling.label, it),
    ),
  ],
}

function toDemoItem(
  roundId: string,
  photoId: string,
  photoLabel: string,
  item: PunchListResult['items'][number],
): DemoItem {
  return {
    id: `${roundId}-${photoId}-${item.id}`,
    title: item.title,
    description: item.description,
    location: `${photoLabel} — ${item.location_in_photo}`,
    trade: item.trade,
    severity: item.severity,
    recommended_action: item.recommended_action,
    sourcePhotoIds: [photoId],
  }
}

// Round 1 item ids, for linking round 2's diff (generated by toDemoItem above).
const R1_CRACK = 'demo-r1-demo-cracked-wall-1'
const R1_COPING = 'demo-r1-demo-cracked-wall-2'
const R1_GRAVEL = 'demo-r1-demo-cracked-wall-3'
const R1_ORGANIC_GROWTH = 'demo-r1-demo-cracked-wall-4'
const R1_CABLE = 'demo-r1-demo-basement-wiring-1'
const R1_PIPE_INSULATION = 'demo-r1-demo-basement-wiring-2'
const R1_WALL_PATCHES = 'demo-r1-demo-basement-wiring-3'
const R1_LOOSE_ITEM = 'demo-r1-demo-basement-wiring-4'
const R1_WATER_STAINING = 'demo-r1-demo-water-damage-ceiling-1'
const R1_PAINT_DELAM = 'demo-r1-demo-water-damage-ceiling-2'
const R1_SHEETROCK = 'demo-r1-demo-water-damage-ceiling-3'

// Round 2 ("30-day re-inspection") intentionally reuses round 1's three
// photos rather than sourcing new ones — labeled explicitly as a
// re-inspection pass. Quick fixes (securing a cable, sweeping gravel,
// painting a patch) are closed on the strength of on-site verification even
// though the archived photo wasn't retaken; the two root-cause items (the
// wall crack and the ceiling leak source) persist, which is why the three
// items downstream of them (organic growth cleanup, paint, sheetrock) also
// remain open — an honest demonstration of round tracking, not a claim that
// these specific photos changed.
const round2: DemoRound = {
  id: 'demo-r2',
  index: 2,
  name: 'Round 2 — 30-day re-inspection',
  projectSummary:
    'Second inspection, 30 days after the initial visit, same three areas. Four issues have ' +
    'been resolved — the exposed cable, wall patches, gravel spill, and a loose stored item. ' +
    'Seven issues persist, most significantly the still-unlocated ceiling leak and the retaining ' +
    'wall crack, both awaiting further diagnosis. Two new issues were noted on closer ' +
    're-inspection: a missing electrical panel cover plate and early efflorescence near the wall crack.',
  progressNotes:
    'Quick, low-cost fixes are being closed out promptly — cable securing, patch painting, and ' +
    'site cleanup all completed within 30 days. The two root-cause items (the ceiling leak source ' +
    "and the wall crack's structural cause) remain undiagnosed and are now the critical path: " +
    "three downstream items (paint, sheetrock, and the wall's organic growth) can't proceed until " +
    'those two are resolved. Recommend prioritizing the leak trace and structural assessment next round.',
  photos: [
    {
      id: 'demo-r2-cracked-wall',
      label: `${crackedWall.label} (re-inspection)`,
      photoPath: crackedWall.photo,
      analysis: {
        scene_summary:
          'Re-inspection of the exterior retaining wall, same vantage as the initial visit. The ' +
          'vertical crack and displaced coping remain; loose gravel at the base has been cleared, ' +
          'and light efflorescence is now visible near the crack.',
        items: [
          {
            id: 1,
            title: 'Vertical crack through retaining wall',
            description:
              'The full-height vertical crack is unchanged in width and extent since the initial ' +
              'inspection; a structural assessment has not yet occurred.',
            location_in_photo: 'Center of the wall, running top to bottom',
            trade: 'concrete',
            severity: 'high',
            recommended_action: 'Proceed with the structural assessment before the next inspection cycle.',
          },
          {
            id: 2,
            title: 'Displaced coping / paver at wall top',
            description:
              'The misaligned paving unit at the wall top has not been re-bedded and still rocks underfoot.',
            location_in_photo: 'Top of the wall, upper-left area',
            trade: 'concrete',
            severity: 'medium',
            recommended_action:
              'Lift, re-bed and re-level; low cost and can be scheduled independently of the structural repair.',
          },
          {
            id: 3,
            title: 'Efflorescence near crack base',
            description:
              'White mineral deposits have begun forming at the base of the vertical crack, consistent ' +
              'with water movement through the crack.',
            location_in_photo: 'Base of the wall, around the crack',
            trade: 'concrete',
            severity: 'low',
            recommended_action: 'Document for the structural engineer; monitor for spread next round.',
          },
          {
            id: 4,
            title: 'Organic growth on wall face',
            description: 'Moss and staining are unchanged; cleanup remains deferred until the structural repair.',
            location_in_photo: 'Left half of the wall face',
            trade: 'general',
            severity: 'low',
            recommended_action: 'Clean after structural repair, as originally planned.',
          },
        ],
      },
    },
    {
      id: 'demo-r2-basement-wiring',
      label: `${basementWiring.label} (re-inspection)`,
      photoPath: basementWiring.photo,
      analysis: {
        scene_summary:
          'Re-inspection of the basement utility room, same vantage. The previously loose cable has ' +
          'been secured and the wall patches painted; a missing panel cover plate was newly noted, ' +
          'and the pipe insulation issue remains open.',
        items: [
          {
            id: 1,
            title: 'Stained / degraded pipe insulation',
            description:
              'Insulation at the stained joints has not yet been replaced; the leak source above has ' +
              'not been confirmed.',
            location_in_photo: 'Ceiling, upper-right pipes',
            trade: 'plumbing',
            severity: 'medium',
            recommended_action: 'Replace insulation once the leak source above is confirmed and repaired.',
          },
          {
            id: 2,
            title: 'Missing panel cover plate',
            description: 'One of the electrical panels is missing its cover plate, exposing live components.',
            location_in_photo: 'Center wall, gray control boxes',
            trade: 'electrical',
            severity: 'medium',
            recommended_action: 'Install an appropriately rated cover plate before the room is signed off.',
          },
        ],
      },
    },
    {
      id: 'demo-r2-water-damage-ceiling',
      label: `${waterDamageCeiling.label} (re-inspection)`,
      photoPath: waterDamageCeiling.photo,
      analysis: {
        scene_summary:
          'Re-inspection of the water-damaged ceiling, same vantage. The leak source has still not ' +
          'been located; staining, paint delamination and the underlying sheetrock concern are all unchanged.',
        items: [
          {
            id: 1,
            title: 'Water staining indicates leak above',
            description: 'Staining is unchanged in extent; the source has still not been traced.',
            location_in_photo: 'Center of the ceiling, within the peeled area',
            trade: 'plumbing',
            severity: 'high',
            recommended_action: 'Prioritize locating the leak source — it now blocks two dependent repairs.',
          },
          {
            id: 2,
            title: 'Extensive paint delamination',
            description: 'Peeling is unchanged; repainting remains blocked on the leak repair.',
            location_in_photo: 'Across the center of the ceiling',
            trade: 'paint',
            severity: 'medium',
            recommended_action: 'Hold until the leak is resolved and the substrate dries.',
          },
          {
            id: 3,
            title: 'Possible sheetrock damage',
            description: 'The board has not yet been probed for softness.',
            location_in_photo: 'Stained area, center of the ceiling',
            trade: 'drywall',
            severity: 'medium',
            recommended_action: 'Probe and assess once safe to access after the leak is addressed.',
          },
        ],
      },
    },
  ],
  items: [
    {
      id: 'demo-r2-crack',
      title: 'Vertical crack through retaining wall',
      description:
        'The full-height vertical crack is unchanged in width and extent since the initial inspection; ' +
        'a structural assessment has not yet occurred.',
      location: 'Cracked retaining wall — center of the wall, running top to bottom',
      trade: 'concrete',
      severity: 'high',
      recommended_action: 'Proceed with the structural assessment before the next inspection cycle.',
      sourcePhotoIds: ['demo-r2-cracked-wall'],
    },
    {
      id: 'demo-r2-coping',
      title: 'Displaced coping / paver at wall top',
      description: 'The misaligned paving unit at the wall top has not been re-bedded and still rocks underfoot.',
      location: 'Cracked retaining wall — top of the wall, upper-left area',
      trade: 'concrete',
      severity: 'medium',
      recommended_action:
        'Lift, re-bed and re-level; low cost and can be scheduled independently of the structural repair.',
      sourcePhotoIds: ['demo-r2-cracked-wall'],
    },
    {
      id: 'demo-r2-organic-growth',
      title: 'Organic growth on wall face',
      description: 'Moss and staining are unchanged; cleanup remains deferred until the structural repair.',
      location: 'Cracked retaining wall — left half of the wall face',
      trade: 'general',
      severity: 'low',
      recommended_action: 'Clean after structural repair, as originally planned.',
      sourcePhotoIds: ['demo-r2-cracked-wall'],
    },
    {
      id: 'demo-r2-pipe-insulation',
      title: 'Stained / degraded pipe insulation',
      description:
        'Insulation at the stained joints has not yet been replaced; the leak source above has not been confirmed.',
      location: 'Basement utility room — ceiling, upper-right pipes',
      trade: 'plumbing',
      severity: 'medium',
      recommended_action: 'Replace insulation once the leak source above is confirmed and repaired.',
      sourcePhotoIds: ['demo-r2-basement-wiring'],
    },
    {
      id: 'demo-r2-water-staining',
      title: 'Water staining indicates leak above',
      description: 'Staining is unchanged in extent; the source has still not been traced.',
      location: 'Water-damaged ceiling — center of the ceiling, within the peeled area',
      trade: 'plumbing',
      severity: 'high',
      recommended_action: 'Prioritize locating the leak source — it now blocks two dependent repairs.',
      sourcePhotoIds: ['demo-r2-water-damage-ceiling'],
    },
    {
      id: 'demo-r2-paint-delam',
      title: 'Extensive paint delamination',
      description: 'Peeling is unchanged; repainting remains blocked on the leak repair.',
      location: 'Water-damaged ceiling — across the center of the ceiling',
      trade: 'paint',
      severity: 'medium',
      recommended_action: 'Hold until the leak is resolved and the substrate dries.',
      sourcePhotoIds: ['demo-r2-water-damage-ceiling'],
    },
    {
      id: 'demo-r2-sheetrock',
      title: 'Possible sheetrock damage',
      description: 'The board has not yet been probed for softness.',
      location: 'Water-damaged ceiling — stained area, center of the ceiling',
      trade: 'drywall',
      severity: 'medium',
      recommended_action: 'Probe and assess once safe to access after the leak is addressed.',
      sourcePhotoIds: ['demo-r2-water-damage-ceiling'],
    },
    {
      id: 'demo-r2-efflorescence',
      title: 'Efflorescence near crack base',
      description:
        'White mineral deposits have begun forming at the base of the vertical crack, consistent with ' +
        'water movement through the crack.',
      location: 'Cracked retaining wall — base of the wall, around the crack',
      trade: 'concrete',
      severity: 'low',
      recommended_action: 'Document for the structural engineer; monitor for spread next round.',
      sourcePhotoIds: ['demo-r2-cracked-wall'],
    },
    {
      id: 'demo-r2-cover-plate',
      title: 'Missing panel cover plate',
      description: 'One of the electrical panels is missing its cover plate, exposing live components.',
      location: 'Basement utility room — center wall, gray control boxes',
      trade: 'electrical',
      severity: 'medium',
      recommended_action: 'Install an appropriately rated cover plate before the room is signed off.',
      sourcePhotoIds: ['demo-r2-basement-wiring'],
    },
  ],
  diff: {
    closed: [R1_GRAVEL, R1_CABLE, R1_WALL_PATCHES, R1_LOOSE_ITEM],
    persistent: [
      { previousId: R1_CRACK, currentId: 'demo-r2-crack', note: 'Unchanged — structural assessment still pending' },
      { previousId: R1_COPING, currentId: 'demo-r2-coping', note: 'Unchanged — not yet re-bedded' },
      {
        previousId: R1_ORGANIC_GROWTH,
        currentId: 'demo-r2-organic-growth',
        note: 'Unchanged — cleanup deferred until structural repair',
      },
      {
        previousId: R1_PIPE_INSULATION,
        currentId: 'demo-r2-pipe-insulation',
        note: 'Unchanged — leak source still unconfirmed',
      },
      {
        previousId: R1_WATER_STAINING,
        currentId: 'demo-r2-water-staining',
        note: 'Unchanged — leak source not yet located',
      },
      { previousId: R1_PAINT_DELAM, currentId: 'demo-r2-paint-delam', note: 'Unchanged — blocked on leak repair' },
      { previousId: R1_SHEETROCK, currentId: 'demo-r2-sheetrock', note: 'Unchanged — not yet probed' },
    ],
    new: ['demo-r2-efflorescence', 'demo-r2-cover-plate'],
  },
}

export const DEMO_DATA = {
  projectName: 'Riverside Build — Demo Project',
  rounds: [round1, round2],
}
