import { SAMPLES } from './samples'
import { BASEMENT_HEIGHT, BUILDING_WIDTH, FLOOR_HEIGHT, WING_CENTER_X, WING_CENTER_Z } from '../lib/twinDimensions'
import type { AskResponse, RiskReportResponse } from '../api'
import type {
  DocumentStatus,
  ExtractedDocument,
  PunchListResult,
  RoundDiff,
  Severity,
  Trade,
  TwinPosition,
} from '../types'

export const DEMO_PROJECT_ID = 'demo'

export interface DemoPhoto {
  id: string
  label: string
  photoPath: string
  analysis: PunchListResult
  twin?: TwinPosition
}

// Hand-picked digital-twin marker positions, referencing the building's
// exported dimension constants so they stay valid if those change.
// - Retaining wall: exterior, just outside the footprint at grade.
// - Basement utility room: below grade, mid-footprint.
// - Water-damaged ceiling: interior, near the underside of level 2.
// - Crack detail: same physical defect as the retaining wall, so it shares
//   that exact position — Markers.tsx stacks same-spot photos automatically.
// - Leaky valve: inside the wing, ground floor.
const TWIN_CRACKED_WALL: TwinPosition = { x: BUILDING_WIDTH / 2 + 3, y: 0, z: 0 }
const TWIN_CRACK_DETAIL: TwinPosition = TWIN_CRACKED_WALL
const TWIN_BASEMENT_WIRING: TwinPosition = { x: -6, y: -BASEMENT_HEIGHT / 2, z: -3 }
const TWIN_WATER_DAMAGE_CEILING: TwinPosition = { x: 4, y: FLOOR_HEIGHT * 2 - 0.3, z: 3 }
const TWIN_LEAKY_VALVE: TwinPosition = { x: WING_CENTER_X, y: FLOOR_HEIGHT / 2 - 0.3, z: WING_CENTER_Z }

export interface DemoItem {
  id: string
  title: string
  description: string
  location: string
  trade: Trade
  severity: Severity
  recommended_action: string
  sourcePhotoIds: string[]
  codeRefs?: { section: string; title: string }[]
}

export interface DemoRound {
  id: string
  index: number
  name: string
  projectSummary: string
  progressNotes: string
  photos: DemoPhoto[]
  items: DemoItem[]
  diff?: RoundDiff
}

const [crackedWall, basementWiring, waterDamageCeiling] = SAMPLES

// Round 1 item ids, referenced below (crack-detail merge) and by round 2's
// diff (generated by toDemoItem, ${roundId}-${photoId}-${item.id}).
const R1_CRACK = 'demo-r1-demo-cracked-wall-1'
const R1_COPING = 'demo-r1-demo-cracked-wall-2'
const R1_GRAVEL = 'demo-r1-demo-cracked-wall-3'
const R1_ORGANIC_GROWTH = 'demo-r1-demo-cracked-wall-4'
const R1_CABLE = 'demo-r1-demo-basement-wiring-1'
const R1_PIPE_INSULATION = 'demo-r1-demo-basement-wiring-2'
const R1_WALL_PATCHES = 'demo-r1-demo-basement-wiring-3'
const R1_LOOSE_ITEM = 'demo-r1-demo-basement-wiring-4'
const R1_WATER_STAINING = 'demo-r1-demo-water-damage-ceiling-1'
const R1_PAINT_DELAM = 'demo-r1-demo-water-damage-ceiling-2'
const R1_SHEETROCK = 'demo-r1-demo-water-damage-ceiling-3'
const R1_LEAKY_VALVE = 'demo-r1-demo-leaky-valve-1'

// A close-up of the same physical crack as the wide retaining-wall shot,
// from a different angle. Merged into the crack item's sourcePhotoIds below
// rather than becoming a second item — this is what /aggregate's dedup
// actually does for two photos of one defect, made visible without an API key.
const crackDetailAnalysis: PunchListResult = {
  scene_summary:
    'Close-up of the vertical crack through the retaining wall, showing the crack width and ' +
    'the broken block face in more detail than the wide shot.',
  items: [
    {
      id: 1,
      title: 'Vertical crack through retaining wall',
      description:
        'Close-up confirms the crack passes fully through the block, not just the mortar joint, ' +
        'with a visible width consistent with ongoing movement rather than a hairline shrinkage crack.',
      location_in_photo: 'Center of frame, running top to bottom',
      trade: 'concrete',
      severity: 'high',
      recommended_action:
        'Have a structural assessment of the crack; monitor width, then rake out and repair with ' +
        'appropriate repair mortar or rebuild the affected section once movement is addressed.',
    },
  ],
}

const leakyValveAnalysis: PunchListResult = {
  scene_summary:
    'Underside of a kitchen sink cabinet, showing the shutoff valve and supply line at the base ' +
    'of the faucet connection with visible corrosion and moisture staining beneath it.',
  items: [
    {
      id: 1,
      title: 'Leaking supply valve beneath sink',
      description:
        'The shutoff valve on the water supply line shows corrosion and moisture staining at the ' +
        'connection, consistent with a slow, ongoing leak rather than a one-time spill.',
      location_in_photo: 'Center, base of the supply line',
      trade: 'plumbing',
      severity: 'medium',
      recommended_action:
        'Replace the valve and supply line; check the cabinet floor beneath for water damage before closing it up.',
    },
  ],
}

// Round 1 reuses the three hand-reviewed sample photos/analyses, plus one
// close-up of the retaining-wall crack and one new area (a leaky sink
// valve), so the demo needs zero API calls. The crack detail photo shares
// a physical defect with the wide retaining-wall shot, so it's merged into
// that item's sources below rather than listed separately — an honest
// reflection of what /aggregate returns for two photos of one defect.
const round1: DemoRound = {
  id: 'demo-r1',
  index: 1,
  name: 'Initial inspection',
  projectSummary:
    'Four areas inspected: an exterior retaining wall (including a close-up of its crack), a ' +
    'basement utility room mid rough-in, an interior ceiling with active water damage, and a ' +
    'kitchen sink with a leaking supply valve. Each area but the sink has at least one ' +
    'high-severity issue requiring attention before work can proceed to the next stage.',
  progressNotes:
    'Site shows mixed progress across areas: exterior hardscape and retaining walls are built but ' +
    'show structural distress, basement electrical/plumbing rough-in is underway with wiring still ' +
    'unsecured, at least one occupied-space ceiling needs remediation before finishes can start, and ' +
    'a kitchen fixture install has a leaking supply valve to correct. No single trade is blocking the ' +
    'others yet, but the ceiling leak should be traced before it does.',
  photos: [
    {
      id: 'demo-cracked-wall',
      label: crackedWall.label,
      photoPath: crackedWall.photo,
      analysis: crackedWall.result,
      twin: TWIN_CRACKED_WALL,
    },
    {
      id: 'demo-crack-detail',
      label: 'Retaining wall crack — close-up',
      photoPath: '/samples/crack-detail.jpg',
      analysis: crackDetailAnalysis,
      twin: TWIN_CRACK_DETAIL,
    },
    {
      id: 'demo-basement-wiring',
      label: basementWiring.label,
      photoPath: basementWiring.photo,
      analysis: basementWiring.result,
      twin: TWIN_BASEMENT_WIRING,
    },
    {
      id: 'demo-water-damage-ceiling',
      label: waterDamageCeiling.label,
      photoPath: waterDamageCeiling.photo,
      analysis: waterDamageCeiling.result,
      twin: TWIN_WATER_DAMAGE_CEILING,
    },
    {
      id: 'demo-leaky-valve',
      label: 'Kitchen sink supply valve',
      photoPath: '/samples/leaky-valve.jpg',
      analysis: leakyValveAnalysis,
      twin: TWIN_LEAKY_VALVE,
    },
  ],
  items: [
    ...crackedWallItems(),
    ...basementWiringItems(),
    ...waterDamageCeiling.result.items.map((it) =>
      toDemoItem('demo-r1', 'demo-water-damage-ceiling', waterDamageCeiling.label, it),
    ),
    ...leakyValveAnalysis.items.map((it) => toDemoItem('demo-r1', 'demo-leaky-valve', 'Kitchen sink supply valve', it)),
  ],
}

// The crack item's sourcePhotoIds gets both the wide shot and the close-up
// — the two-photos-one-defect merge /aggregate would produce.
function crackedWallItems(): DemoItem[] {
  const items = crackedWall.result.items.map((it) => toDemoItem('demo-r1', 'demo-cracked-wall', crackedWall.label, it))
  const crack = items.find((it) => it.id === R1_CRACK)
  if (crack) crack.sourcePhotoIds.push('demo-crack-detail')
  return items
}

// Hand-linked to the OSHA subset in codeCorpus.ts — a genuine fit (exposed
// live circuit, not properly guarded), same discipline as the cover-plate
// item's codeRefs below.
function basementWiringItems(): DemoItem[] {
  const items = basementWiring.result.items.map((it) =>
    toDemoItem('demo-r1', 'demo-basement-wiring', basementWiring.label, it),
  )
  const cable = items.find((it) => it.id === R1_CABLE)
  if (cable) {
    cable.codeRefs = [
      { section: '1926.416(a)(1)', title: 'Electrical — protection of employees, general' },
    ]
  }
  return items
}

function toDemoItem(
  roundId: string,
  photoId: string,
  photoLabel: string,
  item: PunchListResult['items'][number],
): DemoItem {
  return {
    id: `${roundId}-${photoId}-${item.id}`,
    title: item.title,
    description: item.description,
    location: `${photoLabel} — ${item.location_in_photo}`,
    trade: item.trade,
    severity: item.severity,
    recommended_action: item.recommended_action,
    sourcePhotoIds: [photoId],
  }
}

// Round 2 ("30-day re-inspection") intentionally reuses round 1's photos
// rather than sourcing new ones — labeled explicitly as a re-inspection
// pass. Quick fixes (securing a cable, sweeping gravel, painting a patch,
// replacing the leaky valve) are closed on the strength of on-site
// verification even though the archived photo wasn't retaken; the two
// root-cause items (the wall crack and the ceiling leak source) persist,
// which is why the three items downstream of them (organic growth cleanup,
// paint, sheetrock) also remain open — an honest demonstration of round
// tracking, not a claim that these specific photos changed.
const round2: DemoRound = {
  id: 'demo-r2',
  index: 2,
  name: 'Round 2 — 30-day re-inspection',
  projectSummary:
    'Second inspection, 30 days after the initial visit, same four areas. Five issues have ' +
    'been resolved — the exposed cable, wall patches, gravel spill, a loose stored item, and the ' +
    'leaking sink valve. Seven issues persist, most significantly the still-unlocated ceiling leak ' +
    'and the retaining wall crack, both awaiting further diagnosis. Two new issues were noted on ' +
    'closer re-inspection: a missing electrical panel cover plate and early efflorescence near the wall crack.',
  progressNotes:
    'Quick, low-cost fixes are being closed out promptly — cable securing, patch painting, the sink ' +
    'valve replacement, and site cleanup all completed within 30 days. The two root-cause items (the ' +
    "ceiling leak source and the wall crack's structural cause) remain undiagnosed and are now the " +
    "critical path: three downstream items (paint, sheetrock, and the wall's organic growth) can't " +
    'proceed until those two are resolved. Recommend prioritizing the leak trace and structural ' +
    'assessment next round.',
  photos: [
    {
      id: 'demo-r2-cracked-wall',
      label: `${crackedWall.label} (re-inspection)`,
      photoPath: crackedWall.photo,
      analysis: {
        scene_summary:
          'Re-inspection of the exterior retaining wall, same vantage as the initial visit. The ' +
          'vertical crack and displaced coping remain; loose gravel at the base has been cleared, ' +
          'and light efflorescence is now visible near the crack.',
        items: [
          {
            id: 1,
            title: 'Vertical crack through retaining wall',
            description:
              'The full-height vertical crack is unchanged in width and extent since the initial ' +
              'inspection; a structural assessment has not yet occurred.',
            location_in_photo: 'Center of the wall, running top to bottom',
            trade: 'concrete',
            severity: 'high',
            recommended_action: 'Proceed with the structural assessment before the next inspection cycle.',
          },
          {
            id: 2,
            title: 'Displaced coping / paver at wall top',
            description:
              'The misaligned paving unit at the wall top has not been re-bedded and still rocks underfoot.',
            location_in_photo: 'Top of the wall, upper-left area',
            trade: 'concrete',
            severity: 'medium',
            recommended_action:
              'Lift, re-bed and re-level; low cost and can be scheduled independently of the structural repair.',
          },
          {
            id: 3,
            title: 'Efflorescence near crack base',
            description:
              'White mineral deposits have begun forming at the base of the vertical crack, consistent ' +
              'with water movement through the crack.',
            location_in_photo: 'Base of the wall, around the crack',
            trade: 'concrete',
            severity: 'low',
            recommended_action: 'Document for the structural engineer; monitor for spread next round.',
          },
          {
            id: 4,
            title: 'Organic growth on wall face',
            description: 'Moss and staining are unchanged; cleanup remains deferred until the structural repair.',
            location_in_photo: 'Left half of the wall face',
            trade: 'general',
            severity: 'low',
            recommended_action: 'Clean after structural repair, as originally planned.',
          },
        ],
      },
      twin: TWIN_CRACKED_WALL,
    },
    {
      id: 'demo-r2-basement-wiring',
      label: `${basementWiring.label} (re-inspection)`,
      photoPath: basementWiring.photo,
      analysis: {
        scene_summary:
          'Re-inspection of the basement utility room, same vantage. The previously loose cable has ' +
          'been secured and the wall patches painted; a missing panel cover plate was newly noted, ' +
          'and the pipe insulation issue remains open.',
        items: [
          {
            id: 1,
            title: 'Stained / degraded pipe insulation',
            description:
              'Insulation at the stained joints has not yet been replaced; the leak source above has ' +
              'not been confirmed.',
            location_in_photo: 'Ceiling, upper-right pipes',
            trade: 'plumbing',
            severity: 'medium',
            recommended_action: 'Replace insulation once the leak source above is confirmed and repaired.',
          },
          {
            id: 2,
            title: 'Missing panel cover plate',
            description: 'One of the electrical panels is missing its cover plate, exposing live components — a safety hazard, not just a finish item.',
            location_in_photo: 'Center wall, gray control boxes',
            trade: 'safety',
            severity: 'medium',
            recommended_action: 'Install an appropriately rated cover plate before the room is signed off.',
          },
        ],
      },
      twin: TWIN_BASEMENT_WIRING,
    },
    {
      id: 'demo-r2-water-damage-ceiling',
      label: `${waterDamageCeiling.label} (re-inspection)`,
      photoPath: waterDamageCeiling.photo,
      analysis: {
        scene_summary:
          'Re-inspection of the water-damaged ceiling, same vantage. The leak source has still not ' +
          'been located; staining, paint delamination and the underlying sheetrock concern are all unchanged.',
        items: [
          {
            id: 1,
            title: 'Water staining indicates leak above',
            description: 'Staining is unchanged in extent; the source has still not been traced.',
            location_in_photo: 'Center of the ceiling, within the peeled area',
            trade: 'plumbing',
            severity: 'high',
            recommended_action: 'Prioritize locating the leak source — it now blocks two dependent repairs.',
          },
          {
            id: 2,
            title: 'Extensive paint delamination',
            description: 'Peeling is unchanged; repainting remains blocked on the leak repair.',
            location_in_photo: 'Across the center of the ceiling',
            trade: 'paint',
            severity: 'medium',
            recommended_action: 'Hold until the leak is resolved and the substrate dries.',
          },
          {
            id: 3,
            title: 'Possible sheetrock damage',
            description: 'The board has not yet been probed for softness.',
            location_in_photo: 'Stained area, center of the ceiling',
            trade: 'drywall',
            severity: 'medium',
            recommended_action: 'Probe and assess once safe to access after the leak is addressed.',
          },
        ],
      },
      twin: TWIN_WATER_DAMAGE_CEILING,
    },
  ],
  items: [
    {
      id: 'demo-r2-crack',
      title: 'Vertical crack through retaining wall',
      description:
        'The full-height vertical crack is unchanged in width and extent since the initial inspection; ' +
        'a structural assessment has not yet occurred.',
      location: 'Cracked retaining wall — center of the wall, running top to bottom',
      trade: 'concrete',
      severity: 'high',
      recommended_action: 'Proceed with the structural assessment before the next inspection cycle.',
      sourcePhotoIds: ['demo-r2-cracked-wall'],
    },
    {
      id: 'demo-r2-coping',
      title: 'Displaced coping / paver at wall top',
      description: 'The misaligned paving unit at the wall top has not been re-bedded and still rocks underfoot.',
      location: 'Cracked retaining wall — top of the wall, upper-left area',
      trade: 'concrete',
      severity: 'medium',
      recommended_action:
        'Lift, re-bed and re-level; low cost and can be scheduled independently of the structural repair.',
      sourcePhotoIds: ['demo-r2-cracked-wall'],
    },
    {
      id: 'demo-r2-organic-growth',
      title: 'Organic growth on wall face',
      description: 'Moss and staining are unchanged; cleanup remains deferred until the structural repair.',
      location: 'Cracked retaining wall — left half of the wall face',
      trade: 'general',
      severity: 'low',
      recommended_action: 'Clean after structural repair, as originally planned.',
      sourcePhotoIds: ['demo-r2-cracked-wall'],
    },
    {
      id: 'demo-r2-pipe-insulation',
      title: 'Stained / degraded pipe insulation',
      description:
        'Insulation at the stained joints has not yet been replaced; the leak source above has not been confirmed.',
      location: 'Basement utility room — ceiling, upper-right pipes',
      trade: 'plumbing',
      severity: 'medium',
      recommended_action: 'Replace insulation once the leak source above is confirmed and repaired.',
      sourcePhotoIds: ['demo-r2-basement-wiring'],
    },
    {
      id: 'demo-r2-water-staining',
      title: 'Water staining indicates leak above',
      description: 'Staining is unchanged in extent; the source has still not been traced.',
      location: 'Water-damaged ceiling — center of the ceiling, within the peeled area',
      trade: 'plumbing',
      severity: 'high',
      recommended_action: 'Prioritize locating the leak source — it now blocks two dependent repairs.',
      sourcePhotoIds: ['demo-r2-water-damage-ceiling'],
    },
    {
      id: 'demo-r2-paint-delam',
      title: 'Extensive paint delamination',
      description: 'Peeling is unchanged; repainting remains blocked on the leak repair.',
      location: 'Water-damaged ceiling — across the center of the ceiling',
      trade: 'paint',
      severity: 'medium',
      recommended_action: 'Hold until the leak is resolved and the substrate dries.',
      sourcePhotoIds: ['demo-r2-water-damage-ceiling'],
    },
    {
      id: 'demo-r2-sheetrock',
      title: 'Possible sheetrock damage',
      description: 'The board has not yet been probed for softness.',
      location: 'Water-damaged ceiling — stained area, center of the ceiling',
      trade: 'drywall',
      severity: 'medium',
      recommended_action: 'Probe and assess once safe to access after the leak is addressed.',
      sourcePhotoIds: ['demo-r2-water-damage-ceiling'],
    },
    {
      id: 'demo-r2-efflorescence',
      title: 'Efflorescence near crack base',
      description:
        'White mineral deposits have begun forming at the base of the vertical crack, consistent with ' +
        'water movement through the crack.',
      location: 'Cracked retaining wall — base of the wall, around the crack',
      trade: 'concrete',
      severity: 'low',
      recommended_action: 'Document for the structural engineer; monitor for spread next round.',
      sourcePhotoIds: ['demo-r2-cracked-wall'],
    },
    {
      id: 'demo-r2-cover-plate',
      title: 'Missing panel cover plate',
      description: 'One of the electrical panels is missing its cover plate, exposing live components — a safety hazard, not just a finish item.',
      location: 'Basement utility room — center wall, gray control boxes',
      trade: 'safety',
      severity: 'medium',
      recommended_action: 'Install an appropriately rated cover plate before the room is signed off.',
      sourcePhotoIds: ['demo-r2-basement-wiring'],
      codeRefs: [
        { section: '1926.405(b)(2)', title: 'Electrical — cabinets, boxes, and fittings: covers and canopies' },
        { section: '1926.405(d)', title: 'Electrical — switchboards and panelboards' },
      ],
    },
  ],
  diff: {
    closed: [R1_GRAVEL, R1_CABLE, R1_WALL_PATCHES, R1_LOOSE_ITEM, R1_LEAKY_VALVE],
    persistent: [
      { previousId: R1_CRACK, currentId: 'demo-r2-crack', note: 'Unchanged — structural assessment still pending' },
      { previousId: R1_COPING, currentId: 'demo-r2-coping', note: 'Unchanged — not yet re-bedded' },
      {
        previousId: R1_ORGANIC_GROWTH,
        currentId: 'demo-r2-organic-growth',
        note: 'Unchanged — cleanup deferred until structural repair',
      },
      {
        previousId: R1_PIPE_INSULATION,
        currentId: 'demo-r2-pipe-insulation',
        note: 'Unchanged — leak source still unconfirmed',
      },
      {
        previousId: R1_WATER_STAINING,
        currentId: 'demo-r2-water-staining',
        note: 'Unchanged — leak source not yet located',
      },
      { previousId: R1_PAINT_DELAM, currentId: 'demo-r2-paint-delam', note: 'Unchanged — blocked on leak repair' },
      { previousId: R1_SHEETROCK, currentId: 'demo-r2-sheetrock', note: 'Unchanged — not yet probed' },
    ],
    new: ['demo-r2-efflorescence', 'demo-r2-cover-plate'],
  },
}

// Round 3 closes out both root causes that had been blocking downstream work
// since Round 1 — the structural repair and the leak trace both complete
// this round. That unblocks three interior/wall items (none rescheduled
// yet, so they stay open) and, honestly, the repair work itself turns up
// two new findings — a common real-world pattern, not tidied away.
const round3: DemoRound = {
  id: 'demo-r3',
  index: 3,
  name: 'Round 3 — 60-day follow-up',
  projectSummary:
    "Third inspection, 30 days after Round 2. Both structural root causes are now resolved: the " +
    "retaining wall crack was repaired (epoxy injection and reinforcement per the structural " +
    "engineer's assessment) and the ceiling leak was traced to a failed roof flashing and repaired. " +
    "The missing electrical panel cover plate was also installed. No high-severity issues remain " +
    "open — a first for this project. Two new items were noted during the repair work: early " +
    "hairline cracking in the wall section adjacent to the repair, and ceiling insulation that needs " +
    "replacing where it was saturated by the leak before it was fixed.",
  progressNotes:
    "Real momentum this round: both items that had been blocking downstream work for two rounds " +
    "are closed, which immediately unblocks the wall's organic-growth cleanup and the ceiling's " +
    "paint and sheetrock repairs — none are technically blocked anymore, though none have been " +
    "rescheduled yet. The new hairline crack found during the repair excavation is worth watching " +
    "closely; if it behaves like the original crack, it should go to the same structural engineer " +
    "rather than be treated as routine. Recommend closing out the remaining low-priority carryovers " +
    "(coping, pipe insulation) and scheduling the newly-unblocked interior repairs next round.",
  photos: [
    {
      id: 'demo-r3-cracked-wall',
      label: `${crackedWall.label} (follow-up)`,
      photoPath: crackedWall.photo,
      analysis: {
        scene_summary:
          'Follow-up inspection of the retaining wall after the structural repair. Epoxy injection ' +
          'and reinforcement are visible along the former crack line. The displaced coping and base ' +
          'efflorescence are unchanged, and a new hairline crack is visible in the adjacent wall section.',
        items: [
          {
            id: 1,
            title: 'Displaced coping / paver at wall top',
            description: 'The misaligned paving unit at the wall top still has not been re-bedded.',
            location_in_photo: 'Top of the wall, upper-left area',
            trade: 'concrete',
            severity: 'medium',
            recommended_action: 'Lift, re-bed and re-level; low cost, unrelated to the structural repair.',
          },
          {
            id: 2,
            title: 'Organic growth on wall face',
            description: 'Moss and staining are unchanged; cleanup is no longer blocked but not yet scheduled.',
            location_in_photo: 'Left half of the wall face',
            trade: 'general',
            severity: 'low',
            recommended_action: 'Clean with a biocide wash — nothing blocks this anymore.',
          },
          {
            id: 3,
            title: 'Efflorescence near crack base',
            description: 'Mineral deposits remain from before the repair; the crack itself is no longer active.',
            location_in_photo: 'Base of the wall, around the repaired section',
            trade: 'concrete',
            severity: 'low',
            recommended_action: 'Clean residual deposits; no further monitoring needed now that the crack is repaired.',
          },
          {
            id: 4,
            title: 'Early hairline cracking in adjacent wall section',
            description:
              'A fine hairline crack has appeared in the wall section next to the repair, visible during the ' +
              'excavation for the structural work. Too early to tell if it is related or a separate, minor issue.',
            location_in_photo: 'Wall section immediately right of the repaired area',
            trade: 'concrete',
            severity: 'medium',
            recommended_action:
              'Monitor for growth over the next round; loop in the structural engineer if it widens.',
          },
        ],
      },
      twin: TWIN_CRACKED_WALL,
    },
    {
      id: 'demo-r3-basement-wiring',
      label: `${basementWiring.label} (follow-up)`,
      photoPath: basementWiring.photo,
      analysis: {
        scene_summary:
          'Follow-up inspection of the basement utility room. The electrical panel cover plate has ' +
          'been installed; the pipe insulation issue remains open.',
        items: [
          {
            id: 1,
            title: 'Stained / degraded pipe insulation',
            description: 'Insulation has not yet been replaced; the leak source above it is unrelated to the ceiling leak and still unconfirmed.',
            location_in_photo: 'Ceiling, upper-right pipes',
            trade: 'plumbing',
            severity: 'medium',
            recommended_action: 'Replace insulation once its leak source is confirmed and repaired.',
          },
        ],
      },
      twin: TWIN_BASEMENT_WIRING,
    },
    {
      id: 'demo-r3-water-damage-ceiling',
      label: `${waterDamageCeiling.label} (follow-up)`,
      photoPath: waterDamageCeiling.photo,
      analysis: {
        scene_summary:
          'Follow-up inspection of the ceiling. The leak source (a failed roof flashing) has been repaired ' +
          'and the area is dry. Staining and paint delamination remain, unblocked but not yet redone. Opening ' +
          'the cavity to trace the leak revealed saturated insulation that needs replacing.',
        items: [
          {
            id: 1,
            title: 'Extensive paint delamination',
            description: 'Peeling is unchanged; repainting is no longer blocked but not yet scheduled.',
            location_in_photo: 'Across the center of the ceiling',
            trade: 'paint',
            severity: 'medium',
            recommended_action: 'Now that the substrate can dry, scrape, prime and repaint.',
          },
          {
            id: 2,
            title: 'Possible sheetrock damage',
            description: 'The board still has not been probed for softness; access is no longer blocked.',
            location_in_photo: 'Stained area, center of the ceiling',
            trade: 'drywall',
            severity: 'medium',
            recommended_action: 'Probe and assess, then repair as needed.',
          },
          {
            id: 3,
            title: 'Water-stained ceiling insulation requires replacement',
            description:
              'Insulation above the ceiling cavity was saturated by the now-repaired leak and has not dried ' +
              'out; left in place it risks mold regardless of the sheetrock repair.',
            location_in_photo: 'Above the ceiling cavity, visible where opened for the leak trace',
            trade: 'general',
            severity: 'low',
            recommended_action: 'Replace the saturated insulation batts before closing the cavity back up.',
          },
        ],
      },
      twin: TWIN_WATER_DAMAGE_CEILING,
    },
  ],
  items: [
    {
      id: 'demo-r3-coping',
      title: 'Displaced coping / paver at wall top',
      description: 'The misaligned paving unit at the wall top still has not been re-bedded.',
      location: 'Cracked retaining wall — top of the wall, upper-left area',
      trade: 'concrete',
      severity: 'medium',
      recommended_action: 'Lift, re-bed and re-level; low cost, unrelated to the structural repair.',
      sourcePhotoIds: ['demo-r3-cracked-wall'],
    },
    {
      id: 'demo-r3-organic-growth',
      title: 'Organic growth on wall face',
      description: 'Moss and staining are unchanged; cleanup is no longer blocked but not yet scheduled.',
      location: 'Cracked retaining wall — left half of the wall face',
      trade: 'general',
      severity: 'low',
      recommended_action: 'Clean with a biocide wash — nothing blocks this anymore.',
      sourcePhotoIds: ['demo-r3-cracked-wall'],
    },
    {
      id: 'demo-r3-efflorescence',
      title: 'Efflorescence near crack base',
      description: 'Mineral deposits remain from before the repair; the crack itself is no longer active.',
      location: 'Cracked retaining wall — base of the wall, around the repaired section',
      trade: 'concrete',
      severity: 'low',
      recommended_action: 'Clean residual deposits; no further monitoring needed now that the crack is repaired.',
      sourcePhotoIds: ['demo-r3-cracked-wall'],
    },
    {
      id: 'demo-r3-adjacent-crack',
      title: 'Early hairline cracking in adjacent wall section',
      description:
        'A fine hairline crack has appeared in the wall section next to the repair, visible during the ' +
        'excavation for the structural work. Too early to tell if it is related or a separate, minor issue.',
      location: 'Cracked retaining wall — wall section immediately right of the repaired area',
      trade: 'concrete',
      severity: 'medium',
      recommended_action: 'Monitor for growth over the next round; loop in the structural engineer if it widens.',
      sourcePhotoIds: ['demo-r3-cracked-wall'],
    },
    {
      id: 'demo-r3-pipe-insulation',
      title: 'Stained / degraded pipe insulation',
      description: 'Insulation has not yet been replaced; the leak source above it is unrelated to the ceiling leak and still unconfirmed.',
      location: 'Basement utility room — ceiling, upper-right pipes',
      trade: 'plumbing',
      severity: 'medium',
      recommended_action: 'Replace insulation once its leak source is confirmed and repaired.',
      sourcePhotoIds: ['demo-r3-basement-wiring'],
    },
    {
      id: 'demo-r3-paint-delam',
      title: 'Extensive paint delamination',
      description: 'Peeling is unchanged; repainting is no longer blocked but not yet scheduled.',
      location: 'Water-damaged ceiling — across the center of the ceiling',
      trade: 'paint',
      severity: 'medium',
      recommended_action: 'Now that the substrate can dry, scrape, prime and repaint.',
      sourcePhotoIds: ['demo-r3-water-damage-ceiling'],
    },
    {
      id: 'demo-r3-sheetrock',
      title: 'Possible sheetrock damage',
      description: 'The board still has not been probed for softness; access is no longer blocked.',
      location: 'Water-damaged ceiling — stained area, center of the ceiling',
      trade: 'drywall',
      severity: 'medium',
      recommended_action: 'Probe and assess, then repair as needed.',
      sourcePhotoIds: ['demo-r3-water-damage-ceiling'],
    },
    {
      id: 'demo-r3-ceiling-insulation',
      title: 'Water-stained ceiling insulation requires replacement',
      description:
        'Insulation above the ceiling cavity was saturated by the now-repaired leak and has not dried out; ' +
        'left in place it risks mold regardless of the sheetrock repair.',
      location: 'Water-damaged ceiling — above the ceiling cavity, visible where opened for the leak trace',
      trade: 'general',
      severity: 'low',
      recommended_action: 'Replace the saturated insulation batts before closing the cavity back up.',
      sourcePhotoIds: ['demo-r3-water-damage-ceiling'],
    },
  ],
  diff: {
    closed: ['demo-r2-crack', 'demo-r2-water-staining', 'demo-r2-cover-plate'],
    persistent: [
      {
        previousId: 'demo-r2-coping',
        currentId: 'demo-r3-coping',
        note: 'Still not re-bedded — low priority, repeatedly deprioritized',
      },
      {
        previousId: 'demo-r2-organic-growth',
        currentId: 'demo-r3-organic-growth',
        note: 'Unblocked now that the structural repair is complete; cleanup not yet scheduled',
      },
      {
        previousId: 'demo-r2-efflorescence',
        currentId: 'demo-r3-efflorescence',
        note: 'Structural repair complete; residual mineral deposits still need cleaning',
      },
      {
        previousId: 'demo-r2-pipe-insulation',
        currentId: 'demo-r3-pipe-insulation',
        note: "Unchanged — this pipe run's own leak source is still unconfirmed",
      },
      {
        previousId: 'demo-r2-paint-delam',
        currentId: 'demo-r3-paint-delam',
        note: 'Unblocked now that the ceiling leak is fixed; repainting not yet scheduled',
      },
      {
        previousId: 'demo-r2-sheetrock',
        currentId: 'demo-r3-sheetrock',
        note: 'Unblocked now that the ceiling leak is fixed; probe not yet scheduled',
      },
    ],
    new: ['demo-r3-adjacent-crack', 'demo-r3-ceiling-insulation'],
  },
}

export interface DemoDocument {
  id: string
  status: DocumentStatus
  sourceText: string
  extracted: ExtractedDocument
}

function blankExtracted(overrides: Partial<ExtractedDocument>): ExtractedDocument {
  return {
    type: 'notice',
    priority: 'low',
    summary: '',
    subject: '',
    rfi_question: '',
    rfi_discipline: '',
    rfi_reference: '',
    co_description: '',
    co_trade: '',
    co_cost_amount: null,
    co_cost_currency: '',
    co_schedule_impact_days: null,
    co_initiated_by: '',
    notice_type: '',
    notice_body_draft: '',
    ...overrides,
  }
}

// Three pre-extracted example messages so Document Intelligence is
// explorable with zero API key. The change-order text mirrors the exact
// "$3,000 to change the foundation wall from 12\" to 16\"" example from a
// GC/CM discussion of what they wished construction software could do.
const DEMO_DOCUMENTS: DemoDocument[] = [
  {
    id: 'demo-doc-rfi',
    status: 'reviewed',
    sourceText:
      'Hi team, quick question on the mechanical room layout — Sheet M-201 shows the exhaust ' +
      'duct routed along the north wall, but the structural drawing S-104 shows a beam right ' +
      "where that duct is supposed to run. Can you confirm which takes precedence, or if the " +
      'duct needs to be rerouted? Need to know before we frame that wall. Thanks, Dave',
    extracted: blankExtracted({
      type: 'rfi',
      priority: 'high',
      summary:
        'Conflict between the mechanical duct routing on M-201 and a structural beam on S-104 ' +
        'in the mechanical room north wall.',
      subject: 'Duct routing conflict with structural beam — mechanical room north wall',
      rfi_question:
        'Does the structural beam shown on S-104 take precedence over the exhaust duct routing ' +
        'shown on M-201, or does the duct need to be rerouted?',
      rfi_discipline: 'general',
      rfi_reference: 'M-201 (mechanical), S-104 (structural)',
    }),
  },
  {
    id: 'demo-doc-co',
    status: 'reviewed',
    sourceText:
      'Hey, so changing that foundation wall from 12 inches to 16 inches like you asked is ' +
      'going to run an extra $3,000 for the additional concrete and rebar. Let me know if you ' +
      'want me to proceed — Mike',
    extracted: blankExtracted({
      type: 'change_order',
      priority: 'medium',
      summary:
        'Subcontractor requests a $3,000 change order to widen a foundation wall from 12" to 16".',
      subject: 'Foundation wall thickness change — 12" to 16"',
      co_description:
        'Foundation wall thickness increased from 12 inches to 16 inches per request, requiring ' +
        'additional concrete and rebar.',
      co_trade: 'concrete',
      co_cost_amount: 3000,
      co_cost_currency: 'USD',
      co_schedule_impact_days: null, // not stated in the message — left null, not guessed
      co_initiated_by: 'Mike (subcontractor)',
    }),
  },
  {
    id: 'demo-doc-notice',
    status: 'draft',
    sourceText:
      'Just a heads up — the rebar delivery got pushed back to next Thursday because of a ' +
      "supplier issue, so we're going to lose about 3 days on the foundation pour. Wanted to " +
      'flag this before it becomes a bigger problem.',
    extracted: blankExtracted({
      type: 'notice',
      priority: 'high',
      summary:
        'Rebar delivery delayed to next Thursday due to a supplier issue, pushing the ' +
        'foundation pour back approximately 3 days.',
      subject: 'Delay notice — rebar delivery pushed back, foundation pour affected',
      notice_type: 'delay',
      notice_body_draft:
        'Please be advised that the rebar delivery for the foundation pour has been delayed to ' +
        'next Thursday due to a supplier issue. This is expected to push the foundation pour ' +
        'back approximately 3 days. Flagging now to allow for schedule adjustments; will ' +
        'confirm the revised pour date once delivery is reconfirmed.',
    }),
  },
  // These two tie directly into Round 3's punch-list narrative (the crack
  // repair and the new hairline crack found while excavating for it) —
  // showing Document Intelligence and the punch list referencing the same
  // real-world event, not two disconnected demo features.
  {
    id: 'demo-doc-co-repair',
    status: 'reviewed',
    sourceText:
      "Following the structural engineer's report, we're proceeding with epoxy injection and " +
      'carbon fiber reinforcement on the retaining wall crack. This will run $4,200 for materials ' +
      'and labor, and we need about 2 days to complete it before backfilling. Let us know if you ' +
      'want us to proceed — Sam',
    extracted: blankExtracted({
      type: 'change_order',
      priority: 'medium',
      summary:
        'Subcontractor requests a $4,200 change order for epoxy injection and carbon fiber ' +
        'reinforcement to repair the retaining wall crack, needing 2 days before backfilling.',
      subject: 'Retaining wall crack repair — epoxy injection and carbon fiber reinforcement',
      co_description:
        'Epoxy injection and carbon fiber reinforcement to repair the vertical crack in the ' +
        "retaining wall, per the structural engineer's assessment.",
      co_trade: 'concrete',
      co_cost_amount: 4200,
      co_cost_currency: 'USD',
      co_schedule_impact_days: 2,
      co_initiated_by: 'Sam (subcontractor)',
    }),
  },
  {
    id: 'demo-doc-rfi-adjacent-crack',
    status: 'reviewed',
    sourceText:
      'Hey, while we were excavating for the wall repair we noticed a small hairline crack ' +
      "starting in the section right next to it. Doesn't look serious but wanted to flag it — do " +
      'you want the structural engineer to look at this one too while they’re already on site, or ' +
      'should we just keep an eye on it? — Sam',
    extracted: blankExtracted({
      type: 'rfi',
      priority: 'medium',
      summary:
        'A new hairline crack was found adjacent to the retaining wall repair during excavation; ' +
        "asking whether it needs its own structural review or can be monitored.",
      subject: 'New hairline crack adjacent to retaining wall repair — assess or monitor?',
      rfi_question:
        'Should the structural engineer assess the newly-found hairline crack adjacent to the ' +
        'repair while already on site, or is monitoring sufficient for now?',
      rfi_discipline: 'concrete',
      rfi_reference: 'Retaining wall structural repair (in progress)',
    }),
  },
]

export const DEMO_DATA = {
  projectName: 'Riverside Build — Demo Project',
  rounds: [round1, round2, round3],
  documents: DEMO_DOCUMENTS,
}

// Pre-computed answers for the Ask page's suggested questions, so the demo
// project's Q&A is explorable with zero API key and reads identically every
// time. Three are grounded in real seeded data; the fourth deliberately
// demonstrates the honest refusal — asking about something (budget) this
// project genuinely doesn't track, rather than guessing a number.
export const DEMO_SUGGESTED_QUESTIONS: { question: string; answer: AskResponse }[] = [
  {
    question: 'What high-severity issues are still open?',
    answer: {
      answer:
        'None, as of Round 3 — a first for this project. The two high-severity items that were open ' +
        'in Round 2 are both resolved: the retaining wall crack was repaired (epoxy injection and ' +
        'reinforcement) and the ceiling leak source, a failed roof flashing, was fixed. The highest-severity ' +
        "items open now are medium: a new hairline crack found during the repair excavation, and two " +
        'interior repairs that are unblocked but not yet rescheduled.',
      grounded: true,
      citations: [
        { kind: 'item', id: 'demo-r2-crack', label: 'Vertical crack through retaining wall (resolved)' },
        { kind: 'item', id: 'demo-r2-water-staining', label: 'Water staining indicates leak above (resolved)' },
        { kind: 'item', id: 'demo-r3-adjacent-crack', label: 'Early hairline cracking in adjacent wall section' },
      ],
    },
  },
  {
    question: 'What is the total change-order cost impact so far?',
    answer: {
      answer:
        'Two change orders are on record, totaling $7,200: $3,000 to widen the foundation wall from ' +
        '12" to 16", and $4,200 for the epoxy injection and carbon fiber reinforcement that repaired ' +
        'the retaining wall crack in Round 3. No change orders are currently pending a cost figure.',
      grounded: true,
      citations: [
        { kind: 'document', id: 'demo-doc-co', label: 'Foundation wall thickness change — 12" to 16"' },
        { kind: 'document', id: 'demo-doc-co-repair', label: 'Retaining wall crack repair — epoxy injection and carbon fiber reinforcement' },
      ],
    },
  },
  {
    question: 'Has the basement wiring issue been resolved?',
    answer: {
      answer:
        'The electrical side is fully resolved: the unsecured cable was closed in Round 2, and the ' +
        'missing panel cover plate flagged that same round was installed in Round 3. One basement item ' +
        "is still open, but it's plumbing, not electrical — degraded pipe insulation, waiting on its own " +
        "(separate) leak source to be confirmed.",
      grounded: true,
      citations: [
        { kind: 'item', id: 'demo-r1-demo-basement-wiring-1', label: 'Unsecured cable hanging to floor (closed)' },
        { kind: 'item', id: 'demo-r2-cover-plate', label: 'Missing panel cover plate (closed)' },
        { kind: 'item', id: 'demo-r3-pipe-insulation', label: 'Stained / degraded pipe insulation' },
      ],
    },
  },
  {
    question: 'What is the project budget?',
    answer: {
      answer:
        "This project's data doesn't include an overall budget or cost tracking — only the " +
        'dollar amount stated on the one recorded change order ($3,000) is tracked. Answering a ' +
        'total-budget question would require a budget record this project doesn\'t have.',
      grounded: false,
      citations: [],
    },
  },
]

// Pre-computed risk report for the demo project's dashboard, grounded in
// Round 3's eight open items — every reference_ids entry below is a real
// consolidated-item id from round3.items above.
export const DEMO_RISK_REPORT: RiskReportResponse = {
  headline:
    'Both structural root causes are resolved as of Round 3 — for the first time, no high-severity ' +
    'items are open. The top remaining risk is a new hairline crack found during the repair ' +
    "excavation; it's worth watching closely so it doesn't become the project's next root cause.",
  risks: [
    {
      title: 'New hairline crack found adjacent to the repaired wall section',
      severity: 'medium',
      why:
        'Surfaced during the excavation for the structural repair, not from routine inspection. Too ' +
        'early to tell if it shares a cause with the original crack or is unrelated — but it is the ' +
        'only item this round with a plausible path to becoming another multi-round blocker.',
      reference_ids: ['demo-r3-adjacent-crack'],
      recommended_action:
        'Photograph and measure it now to establish a baseline; loop in the same structural engineer ' +
        'if it visibly widens by the next round.',
    },
    {
      title: 'Two interior repairs are unblocked but not yet rescheduled',
      severity: 'medium',
      why:
        'The ceiling leak that had held up the paint and sheetrock repairs for two rounds is fixed, ' +
        "but neither item has moved to a scheduled state yet — the risk now is coordination " +
        'stalling, not a technical blocker.',
      reference_ids: ['demo-r3-paint-delam', 'demo-r3-sheetrock'],
      recommended_action: 'Schedule both repairs now — nothing technical is stopping either one.',
    },
    {
      title: 'Saturated ceiling insulation found during the leak trace',
      severity: 'low',
      why:
        'Opening the ceiling cavity to find the leak source exposed insulation that stayed wet long ' +
        'enough to need replacing, independent of the sheetrock/paint work above it.',
      reference_ids: ['demo-r3-ceiling-insulation'],
      recommended_action: 'Replace the saturated batts before the cavity is closed back up, to avoid trapping moisture.',
    },
    {
      title: 'Remaining low-priority carryovers',
      severity: 'low',
      why:
        'Four items are open but none individually urgent: the wall coping, organic growth, and ' +
        'base efflorescence are cosmetic/low-cost now that the structural cause is fixed, and the ' +
        "basement pipe insulation is waiting on its own (separate, unconfirmed) leak source.",
      reference_ids: ['demo-r3-coping', 'demo-r3-organic-growth', 'demo-r3-efflorescence', 'demo-r3-pipe-insulation'],
      recommended_action: 'Batch these into a single closeout punch-list pass rather than tracking individually.',
    },
  ],
}
