import { SAMPLES } from './samples'
import { BASEMENT_HEIGHT, BUILDING_WIDTH, FLOOR_HEIGHT } from '../lib/twinDimensions'
import type { AskResponse, RiskReportResponse } from '../api'
import type {
  DocumentStatus,
  ExtractedDocument,
  PunchListResult,
  RoundDiff,
  Severity,
  Trade,
  TwinPosition,
} from '../types'

export const DEMO_PROJECT_ID = 'demo'

export interface DemoPhoto {
  id: string
  label: string
  photoPath: string
  analysis: PunchListResult
  twin?: TwinPosition
}

// Hand-picked digital-twin marker positions, referencing the building's
// exported dimension constants so they stay valid if those change.
// - Retaining wall: exterior, just outside the footprint at grade.
// - Basement utility room: below grade, mid-footprint.
// - Water-damaged ceiling: interior, near the underside of level 2.
const TWIN_CRACKED_WALL: TwinPosition = { x: BUILDING_WIDTH / 2 + 3, y: 0, z: 0 }
const TWIN_BASEMENT_WIRING: TwinPosition = { x: -6, y: -BASEMENT_HEIGHT / 2, z: -3 }
const TWIN_WATER_DAMAGE_CEILING: TwinPosition = { x: 4, y: FLOOR_HEIGHT * 2 - 0.3, z: 3 }

export interface DemoItem {
  id: string
  title: string
  description: string
  location: string
  trade: Trade
  severity: Severity
  recommended_action: string
  sourcePhotoIds: string[]
}

export interface DemoRound {
  id: string
  index: number
  name: string
  projectSummary: string
  progressNotes: string
  photos: DemoPhoto[]
  items: DemoItem[]
  diff?: RoundDiff
}

const [crackedWall, basementWiring, waterDamageCeiling] = SAMPLES

// Round 1 reuses the three hand-reviewed sample photos/analyses so the demo
// needs zero API calls. The three scenes don't share a physical location, so
// consolidation here is a straight 1:1 pass-through with project-level
// locations — an honest reflection of what /aggregate would return for a
// set of unrelated areas (no invented merges).
const round1: DemoRound = {
  id: 'demo-r1',
  index: 1,
  name: 'Initial inspection',
  projectSummary:
    'Three areas inspected: an exterior retaining wall, a basement utility room mid rough-in, ' +
    'and an interior ceiling with active water damage. Each area has at least one high-severity ' +
    'issue requiring attention before work can proceed to the next stage.',
  progressNotes:
    'Site shows mixed progress across areas: exterior hardscape and retaining walls are built but ' +
    'show structural distress, basement electrical/plumbing rough-in is underway with wiring still ' +
    'unsecured, and at least one occupied-space ceiling needs remediation before finishes can start. ' +
    'No single trade is blocking the others yet, but the ceiling leak should be traced before it does.',
  photos: [
    {
      id: 'demo-cracked-wall',
      label: crackedWall.label,
      photoPath: crackedWall.photo,
      analysis: crackedWall.result,
      twin: TWIN_CRACKED_WALL,
    },
    {
      id: 'demo-basement-wiring',
      label: basementWiring.label,
      photoPath: basementWiring.photo,
      analysis: basementWiring.result,
      twin: TWIN_BASEMENT_WIRING,
    },
    {
      id: 'demo-water-damage-ceiling',
      label: waterDamageCeiling.label,
      photoPath: waterDamageCeiling.photo,
      analysis: waterDamageCeiling.result,
      twin: TWIN_WATER_DAMAGE_CEILING,
    },
  ],
  items: [
    ...crackedWall.result.items.map((it) => toDemoItem('demo-r1', 'demo-cracked-wall', crackedWall.label, it)),
    ...basementWiring.result.items.map((it) =>
      toDemoItem('demo-r1', 'demo-basement-wiring', basementWiring.label, it),
    ),
    ...waterDamageCeiling.result.items.map((it) =>
      toDemoItem('demo-r1', 'demo-water-damage-ceiling', waterDamageCeiling.label, it),
    ),
  ],
}

function toDemoItem(
  roundId: string,
  photoId: string,
  photoLabel: string,
  item: PunchListResult['items'][number],
): DemoItem {
  return {
    id: `${roundId}-${photoId}-${item.id}`,
    title: item.title,
    description: item.description,
    location: `${photoLabel} — ${item.location_in_photo}`,
    trade: item.trade,
    severity: item.severity,
    recommended_action: item.recommended_action,
    sourcePhotoIds: [photoId],
  }
}

// Round 1 item ids, for linking round 2's diff (generated by toDemoItem above).
const R1_CRACK = 'demo-r1-demo-cracked-wall-1'
const R1_COPING = 'demo-r1-demo-cracked-wall-2'
const R1_GRAVEL = 'demo-r1-demo-cracked-wall-3'
const R1_ORGANIC_GROWTH = 'demo-r1-demo-cracked-wall-4'
const R1_CABLE = 'demo-r1-demo-basement-wiring-1'
const R1_PIPE_INSULATION = 'demo-r1-demo-basement-wiring-2'
const R1_WALL_PATCHES = 'demo-r1-demo-basement-wiring-3'
const R1_LOOSE_ITEM = 'demo-r1-demo-basement-wiring-4'
const R1_WATER_STAINING = 'demo-r1-demo-water-damage-ceiling-1'
const R1_PAINT_DELAM = 'demo-r1-demo-water-damage-ceiling-2'
const R1_SHEETROCK = 'demo-r1-demo-water-damage-ceiling-3'

// Round 2 ("30-day re-inspection") intentionally reuses round 1's three
// photos rather than sourcing new ones — labeled explicitly as a
// re-inspection pass. Quick fixes (securing a cable, sweeping gravel,
// painting a patch) are closed on the strength of on-site verification even
// though the archived photo wasn't retaken; the two root-cause items (the
// wall crack and the ceiling leak source) persist, which is why the three
// items downstream of them (organic growth cleanup, paint, sheetrock) also
// remain open — an honest demonstration of round tracking, not a claim that
// these specific photos changed.
const round2: DemoRound = {
  id: 'demo-r2',
  index: 2,
  name: 'Round 2 — 30-day re-inspection',
  projectSummary:
    'Second inspection, 30 days after the initial visit, same three areas. Four issues have ' +
    'been resolved — the exposed cable, wall patches, gravel spill, and a loose stored item. ' +
    'Seven issues persist, most significantly the still-unlocated ceiling leak and the retaining ' +
    'wall crack, both awaiting further diagnosis. Two new issues were noted on closer ' +
    're-inspection: a missing electrical panel cover plate and early efflorescence near the wall crack.',
  progressNotes:
    'Quick, low-cost fixes are being closed out promptly — cable securing, patch painting, and ' +
    'site cleanup all completed within 30 days. The two root-cause items (the ceiling leak source ' +
    "and the wall crack's structural cause) remain undiagnosed and are now the critical path: " +
    "three downstream items (paint, sheetrock, and the wall's organic growth) can't proceed until " +
    'those two are resolved. Recommend prioritizing the leak trace and structural assessment next round.',
  photos: [
    {
      id: 'demo-r2-cracked-wall',
      label: `${crackedWall.label} (re-inspection)`,
      photoPath: crackedWall.photo,
      analysis: {
        scene_summary:
          'Re-inspection of the exterior retaining wall, same vantage as the initial visit. The ' +
          'vertical crack and displaced coping remain; loose gravel at the base has been cleared, ' +
          'and light efflorescence is now visible near the crack.',
        items: [
          {
            id: 1,
            title: 'Vertical crack through retaining wall',
            description:
              'The full-height vertical crack is unchanged in width and extent since the initial ' +
              'inspection; a structural assessment has not yet occurred.',
            location_in_photo: 'Center of the wall, running top to bottom',
            trade: 'concrete',
            severity: 'high',
            recommended_action: 'Proceed with the structural assessment before the next inspection cycle.',
          },
          {
            id: 2,
            title: 'Displaced coping / paver at wall top',
            description:
              'The misaligned paving unit at the wall top has not been re-bedded and still rocks underfoot.',
            location_in_photo: 'Top of the wall, upper-left area',
            trade: 'concrete',
            severity: 'medium',
            recommended_action:
              'Lift, re-bed and re-level; low cost and can be scheduled independently of the structural repair.',
          },
          {
            id: 3,
            title: 'Efflorescence near crack base',
            description:
              'White mineral deposits have begun forming at the base of the vertical crack, consistent ' +
              'with water movement through the crack.',
            location_in_photo: 'Base of the wall, around the crack',
            trade: 'concrete',
            severity: 'low',
            recommended_action: 'Document for the structural engineer; monitor for spread next round.',
          },
          {
            id: 4,
            title: 'Organic growth on wall face',
            description: 'Moss and staining are unchanged; cleanup remains deferred until the structural repair.',
            location_in_photo: 'Left half of the wall face',
            trade: 'general',
            severity: 'low',
            recommended_action: 'Clean after structural repair, as originally planned.',
          },
        ],
      },
      twin: TWIN_CRACKED_WALL,
    },
    {
      id: 'demo-r2-basement-wiring',
      label: `${basementWiring.label} (re-inspection)`,
      photoPath: basementWiring.photo,
      analysis: {
        scene_summary:
          'Re-inspection of the basement utility room, same vantage. The previously loose cable has ' +
          'been secured and the wall patches painted; a missing panel cover plate was newly noted, ' +
          'and the pipe insulation issue remains open.',
        items: [
          {
            id: 1,
            title: 'Stained / degraded pipe insulation',
            description:
              'Insulation at the stained joints has not yet been replaced; the leak source above has ' +
              'not been confirmed.',
            location_in_photo: 'Ceiling, upper-right pipes',
            trade: 'plumbing',
            severity: 'medium',
            recommended_action: 'Replace insulation once the leak source above is confirmed and repaired.',
          },
          {
            id: 2,
            title: 'Missing panel cover plate',
            description: 'One of the electrical panels is missing its cover plate, exposing live components.',
            location_in_photo: 'Center wall, gray control boxes',
            trade: 'electrical',
            severity: 'medium',
            recommended_action: 'Install an appropriately rated cover plate before the room is signed off.',
          },
        ],
      },
      twin: TWIN_BASEMENT_WIRING,
    },
    {
      id: 'demo-r2-water-damage-ceiling',
      label: `${waterDamageCeiling.label} (re-inspection)`,
      photoPath: waterDamageCeiling.photo,
      analysis: {
        scene_summary:
          'Re-inspection of the water-damaged ceiling, same vantage. The leak source has still not ' +
          'been located; staining, paint delamination and the underlying sheetrock concern are all unchanged.',
        items: [
          {
            id: 1,
            title: 'Water staining indicates leak above',
            description: 'Staining is unchanged in extent; the source has still not been traced.',
            location_in_photo: 'Center of the ceiling, within the peeled area',
            trade: 'plumbing',
            severity: 'high',
            recommended_action: 'Prioritize locating the leak source — it now blocks two dependent repairs.',
          },
          {
            id: 2,
            title: 'Extensive paint delamination',
            description: 'Peeling is unchanged; repainting remains blocked on the leak repair.',
            location_in_photo: 'Across the center of the ceiling',
            trade: 'paint',
            severity: 'medium',
            recommended_action: 'Hold until the leak is resolved and the substrate dries.',
          },
          {
            id: 3,
            title: 'Possible sheetrock damage',
            description: 'The board has not yet been probed for softness.',
            location_in_photo: 'Stained area, center of the ceiling',
            trade: 'drywall',
            severity: 'medium',
            recommended_action: 'Probe and assess once safe to access after the leak is addressed.',
          },
        ],
      },
      twin: TWIN_WATER_DAMAGE_CEILING,
    },
  ],
  items: [
    {
      id: 'demo-r2-crack',
      title: 'Vertical crack through retaining wall',
      description:
        'The full-height vertical crack is unchanged in width and extent since the initial inspection; ' +
        'a structural assessment has not yet occurred.',
      location: 'Cracked retaining wall — center of the wall, running top to bottom',
      trade: 'concrete',
      severity: 'high',
      recommended_action: 'Proceed with the structural assessment before the next inspection cycle.',
      sourcePhotoIds: ['demo-r2-cracked-wall'],
    },
    {
      id: 'demo-r2-coping',
      title: 'Displaced coping / paver at wall top',
      description: 'The misaligned paving unit at the wall top has not been re-bedded and still rocks underfoot.',
      location: 'Cracked retaining wall — top of the wall, upper-left area',
      trade: 'concrete',
      severity: 'medium',
      recommended_action:
        'Lift, re-bed and re-level; low cost and can be scheduled independently of the structural repair.',
      sourcePhotoIds: ['demo-r2-cracked-wall'],
    },
    {
      id: 'demo-r2-organic-growth',
      title: 'Organic growth on wall face',
      description: 'Moss and staining are unchanged; cleanup remains deferred until the structural repair.',
      location: 'Cracked retaining wall — left half of the wall face',
      trade: 'general',
      severity: 'low',
      recommended_action: 'Clean after structural repair, as originally planned.',
      sourcePhotoIds: ['demo-r2-cracked-wall'],
    },
    {
      id: 'demo-r2-pipe-insulation',
      title: 'Stained / degraded pipe insulation',
      description:
        'Insulation at the stained joints has not yet been replaced; the leak source above has not been confirmed.',
      location: 'Basement utility room — ceiling, upper-right pipes',
      trade: 'plumbing',
      severity: 'medium',
      recommended_action: 'Replace insulation once the leak source above is confirmed and repaired.',
      sourcePhotoIds: ['demo-r2-basement-wiring'],
    },
    {
      id: 'demo-r2-water-staining',
      title: 'Water staining indicates leak above',
      description: 'Staining is unchanged in extent; the source has still not been traced.',
      location: 'Water-damaged ceiling — center of the ceiling, within the peeled area',
      trade: 'plumbing',
      severity: 'high',
      recommended_action: 'Prioritize locating the leak source — it now blocks two dependent repairs.',
      sourcePhotoIds: ['demo-r2-water-damage-ceiling'],
    },
    {
      id: 'demo-r2-paint-delam',
      title: 'Extensive paint delamination',
      description: 'Peeling is unchanged; repainting remains blocked on the leak repair.',
      location: 'Water-damaged ceiling — across the center of the ceiling',
      trade: 'paint',
      severity: 'medium',
      recommended_action: 'Hold until the leak is resolved and the substrate dries.',
      sourcePhotoIds: ['demo-r2-water-damage-ceiling'],
    },
    {
      id: 'demo-r2-sheetrock',
      title: 'Possible sheetrock damage',
      description: 'The board has not yet been probed for softness.',
      location: 'Water-damaged ceiling — stained area, center of the ceiling',
      trade: 'drywall',
      severity: 'medium',
      recommended_action: 'Probe and assess once safe to access after the leak is addressed.',
      sourcePhotoIds: ['demo-r2-water-damage-ceiling'],
    },
    {
      id: 'demo-r2-efflorescence',
      title: 'Efflorescence near crack base',
      description:
        'White mineral deposits have begun forming at the base of the vertical crack, consistent with ' +
        'water movement through the crack.',
      location: 'Cracked retaining wall — base of the wall, around the crack',
      trade: 'concrete',
      severity: 'low',
      recommended_action: 'Document for the structural engineer; monitor for spread next round.',
      sourcePhotoIds: ['demo-r2-cracked-wall'],
    },
    {
      id: 'demo-r2-cover-plate',
      title: 'Missing panel cover plate',
      description: 'One of the electrical panels is missing its cover plate, exposing live components.',
      location: 'Basement utility room — center wall, gray control boxes',
      trade: 'electrical',
      severity: 'medium',
      recommended_action: 'Install an appropriately rated cover plate before the room is signed off.',
      sourcePhotoIds: ['demo-r2-basement-wiring'],
    },
  ],
  diff: {
    closed: [R1_GRAVEL, R1_CABLE, R1_WALL_PATCHES, R1_LOOSE_ITEM],
    persistent: [
      { previousId: R1_CRACK, currentId: 'demo-r2-crack', note: 'Unchanged — structural assessment still pending' },
      { previousId: R1_COPING, currentId: 'demo-r2-coping', note: 'Unchanged — not yet re-bedded' },
      {
        previousId: R1_ORGANIC_GROWTH,
        currentId: 'demo-r2-organic-growth',
        note: 'Unchanged — cleanup deferred until structural repair',
      },
      {
        previousId: R1_PIPE_INSULATION,
        currentId: 'demo-r2-pipe-insulation',
        note: 'Unchanged — leak source still unconfirmed',
      },
      {
        previousId: R1_WATER_STAINING,
        currentId: 'demo-r2-water-staining',
        note: 'Unchanged — leak source not yet located',
      },
      { previousId: R1_PAINT_DELAM, currentId: 'demo-r2-paint-delam', note: 'Unchanged — blocked on leak repair' },
      { previousId: R1_SHEETROCK, currentId: 'demo-r2-sheetrock', note: 'Unchanged — not yet probed' },
    ],
    new: ['demo-r2-efflorescence', 'demo-r2-cover-plate'],
  },
}

export interface DemoDocument {
  id: string
  status: DocumentStatus
  sourceText: string
  extracted: ExtractedDocument
}

function blankExtracted(overrides: Partial<ExtractedDocument>): ExtractedDocument {
  return {
    type: 'notice',
    priority: 'low',
    summary: '',
    subject: '',
    rfi_question: '',
    rfi_discipline: '',
    rfi_reference: '',
    co_description: '',
    co_trade: '',
    co_cost_amount: null,
    co_cost_currency: '',
    co_schedule_impact_days: null,
    co_initiated_by: '',
    notice_type: '',
    notice_body_draft: '',
    ...overrides,
  }
}

// Three pre-extracted example messages so Document Intelligence is
// explorable with zero API key. The change-order text mirrors the exact
// "$3,000 to change the foundation wall from 12\" to 16\"" example from a
// GC/CM discussion of what they wished construction software could do.
const DEMO_DOCUMENTS: DemoDocument[] = [
  {
    id: 'demo-doc-rfi',
    status: 'reviewed',
    sourceText:
      'Hi team, quick question on the mechanical room layout — Sheet M-201 shows the exhaust ' +
      'duct routed along the north wall, but the structural drawing S-104 shows a beam right ' +
      "where that duct is supposed to run. Can you confirm which takes precedence, or if the " +
      'duct needs to be rerouted? Need to know before we frame that wall. Thanks, Dave',
    extracted: blankExtracted({
      type: 'rfi',
      priority: 'high',
      summary:
        'Conflict between the mechanical duct routing on M-201 and a structural beam on S-104 ' +
        'in the mechanical room north wall.',
      subject: 'Duct routing conflict with structural beam — mechanical room north wall',
      rfi_question:
        'Does the structural beam shown on S-104 take precedence over the exhaust duct routing ' +
        'shown on M-201, or does the duct need to be rerouted?',
      rfi_discipline: 'general',
      rfi_reference: 'M-201 (mechanical), S-104 (structural)',
    }),
  },
  {
    id: 'demo-doc-co',
    status: 'reviewed',
    sourceText:
      'Hey, so changing that foundation wall from 12 inches to 16 inches like you asked is ' +
      'going to run an extra $3,000 for the additional concrete and rebar. Let me know if you ' +
      'want me to proceed — Mike',
    extracted: blankExtracted({
      type: 'change_order',
      priority: 'medium',
      summary:
        'Subcontractor requests a $3,000 change order to widen a foundation wall from 12" to 16".',
      subject: 'Foundation wall thickness change — 12" to 16"',
      co_description:
        'Foundation wall thickness increased from 12 inches to 16 inches per request, requiring ' +
        'additional concrete and rebar.',
      co_trade: 'concrete',
      co_cost_amount: 3000,
      co_cost_currency: 'USD',
      co_schedule_impact_days: null, // not stated in the message — left null, not guessed
      co_initiated_by: 'Mike (subcontractor)',
    }),
  },
  {
    id: 'demo-doc-notice',
    status: 'draft',
    sourceText:
      'Just a heads up — the rebar delivery got pushed back to next Thursday because of a ' +
      "supplier issue, so we're going to lose about 3 days on the foundation pour. Wanted to " +
      'flag this before it becomes a bigger problem.',
    extracted: blankExtracted({
      type: 'notice',
      priority: 'high',
      summary:
        'Rebar delivery delayed to next Thursday due to a supplier issue, pushing the ' +
        'foundation pour back approximately 3 days.',
      subject: 'Delay notice — rebar delivery pushed back, foundation pour affected',
      notice_type: 'delay',
      notice_body_draft:
        'Please be advised that the rebar delivery for the foundation pour has been delayed to ' +
        'next Thursday due to a supplier issue. This is expected to push the foundation pour ' +
        'back approximately 3 days. Flagging now to allow for schedule adjustments; will ' +
        'confirm the revised pour date once delivery is reconfirmed.',
    }),
  },
]

export const DEMO_DATA = {
  projectName: 'Riverside Build — Demo Project',
  rounds: [round1, round2],
  documents: DEMO_DOCUMENTS,
}

// Pre-computed answers for the Ask page's suggested questions, so the demo
// project's Q&A is explorable with zero API key and reads identically every
// time. Three are grounded in real seeded data; the fourth deliberately
// demonstrates the honest refusal — asking about something (budget) this
// project genuinely doesn't track, rather than guessing a number.
export const DEMO_SUGGESTED_QUESTIONS: { question: string; answer: AskResponse }[] = [
  {
    question: 'What high-severity issues are still open?',
    answer: {
      answer:
        'Two high-severity items are still open as of Round 2: the vertical crack through the ' +
        'retaining wall, which is still awaiting a structural assessment, and the water staining ' +
        'on the ceiling, whose leak source has still not been located and is now blocking two ' +
        'dependent repairs (paint and sheetrock).',
      grounded: true,
      citations: [
        { kind: 'item', id: 'demo-r2-crack', label: 'Vertical crack through retaining wall' },
        { kind: 'item', id: 'demo-r2-water-staining', label: 'Water staining indicates leak above' },
      ],
    },
  },
  {
    question: 'What is the total change-order cost impact so far?',
    answer: {
      answer:
        'One change order is on record: widening the foundation wall from 12" to 16" for ' +
        'additional concrete and rebar, at a stated cost of $3,000. No change orders are ' +
        'currently pending a cost figure.',
      grounded: true,
      citations: [
        { kind: 'document', id: 'demo-doc-co', label: 'Foundation wall thickness change — 12" to 16"' },
      ],
    },
  },
  {
    question: 'Has the basement wiring issue been resolved?',
    answer: {
      answer:
        'Partially. The originally unsecured cable was closed in Round 2 — it was secured on ' +
        'site. But a new issue was flagged in that same re-inspection: one of the electrical ' +
        "panels is missing its cover plate, so the basement electrical work isn't fully clear yet.",
      grounded: true,
      citations: [
        { kind: 'item', id: 'demo-r1-demo-basement-wiring-1', label: 'Unsecured cable hanging to floor (closed)' },
        { kind: 'item', id: 'demo-r2-cover-plate', label: 'Missing panel cover plate' },
      ],
    },
  },
  {
    question: 'What is the project budget?',
    answer: {
      answer:
        "This project's data doesn't include an overall budget or cost tracking — only the " +
        'dollar amount stated on the one recorded change order ($3,000) is tracked. Answering a ' +
        'total-budget question would require a budget record this project doesn\'t have.',
      grounded: false,
      citations: [],
    },
  },
]

// Pre-computed risk report for the demo project's dashboard, grounded in
// Round 2's nine open items — every reference_ids entry below is a real
// consolidated-item id from round2.items above.
export const DEMO_RISK_REPORT: RiskReportResponse = {
  headline:
    'Two unresolved root causes — the ceiling leak source and the retaining wall crack — are ' +
    'now blocking five of the nine open items; resolving those two unblocks the rest of the ' +
    'project faster than working the list top-down.',
  risks: [
    {
      title: 'Ceiling leak source still unlocated — now blocking two dependent repairs',
      severity: 'high',
      why:
        "The water-damage source hasn't been traced across two inspection rounds, and it's now " +
        "the stated reason two other items (paint delamination, sheetrock probe) can't proceed. " +
        'This is the item most likely to cascade into further delay.',
      reference_ids: ['demo-r2-water-staining', 'demo-r2-paint-delam', 'demo-r2-sheetrock'],
      recommended_action:
        'Prioritize a plumbing/roofing trace to locate the leak source before the next ' +
        'inspection round — this unblocks two downstream items at once.',
    },
    {
      title: 'Retaining wall crack unresolved — structural assessment still pending',
      severity: 'high',
      why:
        'The crack has been open since Round 1 with no visible change. A structural engineer has ' +
        'not yet been engaged, and the coping repair, organic-growth cleanup, and newly-noted ' +
        'efflorescence on the same wall are all effectively waiting on this one decision.',
      reference_ids: ['demo-r2-crack', 'demo-r2-coping', 'demo-r2-organic-growth', 'demo-r2-efflorescence'],
      recommended_action:
        'Schedule the structural assessment — three other wall items are blocked on this decision.',
    },
    {
      title: 'Exposed live electrical components in the basement',
      severity: 'medium',
      why:
        'A missing panel cover plate was newly flagged this round, leaving live components ' +
        'exposed. This is a safety item that should close quickly rather than carry into ' +
        'another round.',
      reference_ids: ['demo-r2-cover-plate'],
      recommended_action:
        'Install the correct cover plate before the room is signed off — low cost, no reason to wait.',
    },
    {
      title: 'Pipe insulation replacement pending leak confirmation',
      severity: 'medium',
      why:
        'Degraded insulation in the basement utility room is a lower-urgency item tied to the ' +
        'same undiagnosed ceiling leak.',
      reference_ids: ['demo-r2-pipe-insulation'],
      recommended_action: 'Replace once the leak source is confirmed and repaired — no separate action needed before then.',
    },
  ],
}
