import type { PunchListResult } from './types'

export async function exportPdf(result: PunchListResult, photoLabel: string) {
  // Loaded on demand so the PDF library stays out of the initial bundle.
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])
  const doc = new jsPDF()
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  doc.setFontSize(18)
  doc.setTextColor(234, 88, 12)
  doc.text('PunchList AI — Site Inspection Report', 14, 18)

  doc.setFontSize(10)
  doc.setTextColor(80)
  doc.text(`Photo: ${photoLabel}`, 14, 26)
  doc.text(`Generated: ${date}`, 14, 31)

  doc.setFontSize(11)
  doc.setTextColor(40)
  const summary = doc.splitTextToSize(result.scene_summary, 180)
  doc.text(summary, 14, 40)

  autoTable(doc, {
    startY: 40 + summary.length * 5 + 4,
    head: [['#', 'Issue', 'Location', 'Trade', 'Severity', 'Recommended action']],
    body: result.items.map((it) => [
      String(it.id),
      `${it.title}\n${it.description}`,
      it.location_in_photo,
      it.trade,
      it.severity.toUpperCase(),
      it.recommended_action,
    ]),
    styles: { fontSize: 8, cellPadding: 2, valign: 'top' },
    headStyles: { fillColor: [234, 88, 12] },
    columnStyles: {
      0: { cellWidth: 8 },
      1: { cellWidth: 55 },
      2: { cellWidth: 32 },
      3: { cellWidth: 20 },
      4: { cellWidth: 18 },
      5: { cellWidth: 48 },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 4) {
        const sev = String(data.cell.raw)
        if (sev === 'HIGH') data.cell.styles.textColor = [220, 38, 38]
        else if (sev === 'MEDIUM') data.cell.styles.textColor = [217, 119, 6]
        else data.cell.styles.textColor = [22, 163, 74]
        data.cell.styles.fontStyle = 'bold'
      }
    },
  })

  doc.setFontSize(8)
  doc.setTextColor(150)
  doc.text(
    'Generated by PunchList AI (demo). Not a substitute for professional inspection.',
    14,
    doc.internal.pageSize.height - 8,
  )

  doc.save(`punchlist-${photoLabel.toLowerCase().replace(/\s+/g, '-')}.pdf`)
}
